on: push

jobs:
  test_and_build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Load cache
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
          path: |
            ~/.cache/Cypress
            node_modules
            .next/cache

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup node, cache
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
          cache-dependency-path: "**/pnpm-lock.yaml"

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Setup Pages
        uses: actions/configure-pages@v3
        with:
          static_site_generator: next

      - name: Check TS & ESLint
        run: pnpm check

      - name: Build
        run: pnpm build

      # - name: Install Cypress
      #   run: pnpm cypress install

      # - name: Cypress E2E Firefox
      #   uses: cypress-io/github-action@v6
      #   with:
      #     browser: firefox
      #     start: npm start
      #     wait-on: "http://localhost:3000"

      # - name: Cypress E2E Chrome
      #   uses: cypress-io/github-action@v6
      #   with:
      #     browser: chrome
      #     start: npm start
      #     wait-on: "http://localhost:3000"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./out"

  deploy:
    needs: test_and_build
    runs-on: ubuntu-24.04
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        id: deployment
        uses: actions/deploy-pages@v2
