on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_deploy:
    # For faster builds, use larger runners (requires GitHub Team/Enterprise):
    # runs-on: ubuntu-latest-4-cores
    # runs-on: ubuntu-latest-8-cores
    runs-on: ubuntu-24.04
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Load cache
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-build-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-
          path: |
            node_modules
            .next/cache

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup node, cache
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          static_site_generator: next

      - name: Check TypeScript
        run: pnpm check:tsc
        
      - name: Check ESLint
        run: pnpm check:lint

      - name: Build with Turbo
        run: pnpm build

      # - name: Install Cypress
      #   run: pnpm cypress install

      # - name: Cypress E2E Firefox
      #   uses: cypress-io/github-action@v6
      #   with:
      #     browser: firefox
      #     start: npm start
      #     wait-on: "http://localhost:3000"

      # - name: Cypress E2E Chrome
      #   uses: cypress-io/github-action@v6
      #   with:
      #     browser: chrome
      #     start: npm start
      #     wait-on: "http://localhost:3000"

      - name: Upload artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./out"
          retention-days: 7

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        id: deployment
        uses: actions/deploy-pages@v4
